name: agriculture_auth
description: Modern authentication UI for agriculture platform with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Image picker for profile picture upload
  flutter_map: ^8.2.2
  http: ^1.6.0
  image_picker: ^1.0.4
  latlong2: ^0.9.1
  pdf: ^3.11.3
  printing: ^5.14.2
  provider: ^6.1.5+1
  quickalert: ^1.1.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

